POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email": "rohankurella02@gmail.com",
    "password": "rohan@123"
}

#######
GET http://localhost:4000/api/post/get


######
PATCH http://localhost:4000/api/post/updateLikeCount/63922996f7e54069e3008d9c
Content-Type: application/json

{
    "likeCounter": 1
}


######
POST http://localhost:4000/api/post/create
Content-Type: application/json

{
    "profileImageUrl": "https://media-exp1.licdn.com/dms/image/C5603AQHqCvB-aXScDA/profile-displayphoto-shrink_100_100/0/1643689799279?e=1676505600&v=beta&t=BzYill2HIxXBrdtHWrYug8BDkDnzPkb9sqzDjfAXBGE",
    "profileName": "Rohan Kurella",
    "message": "This is a test post",
    "photoUrl": "https://media-exp1.licdn.com/dms/image/C5622AQE-d3KmFBSR_g/feedshare-shrink_800/0/1670603234645?e=1673481600&v=beta&t=jRvi_91fZVlJp9yxlBC2ICiNocK0SHyLMGJdTNSy2Ps",
    "likeCounter": 367,
    "commentCounter": 23
}

######
DELETE http://localhost:4000/api/post/delete/6395e30d4015881f1c31a8d5
